import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

import ResponsiveNav from "../components/Home/Navbar/ResponsiveNav";
import Provider from "../components/Hoc/Provider";
import Footer from "../components/Home/Footer/Footer";
import ScrollToTop from "../components/Helper/ScrollToTop";
import { GoogleOAuthProvider } from "@react-oauth/google";   // ✅ Thêm
import AuthProvider from "../context/AuthContext";            // Bạn đã có

const font = Roboto({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "JobNest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning={true} className={`${font.className} antialiased`}>

        {/* 🟦 BỌC TOÀN BỘ APP TRONG Google Provider */}
        <GoogleOAuthProvider clientId="737701980832-9ustssqhaf802gjd4e31h2jsukml88kv.apps.googleusercontent.com">

          {/* 🟩 Bên trong là AuthProvider + UI */}
          <AuthProvider>
            <Provider>
              <ResponsiveNav />
              {children}
              <Footer />
              <ScrollToTop />
            </Provider>
          </AuthProvider>


        </GoogleOAuthProvider>

      </body>
    </html>
  );
}
