import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "../../components/Home/Navbar/ResponsiveNav";
import Provider from "../../components/Hoc/Provider";
import Footer from "../../components/Home/Footer/Footer";
import ScrollToTop from "../../components/Helper/ScrollToTop";

// ✅ Add this import
import AuthProvider from "../context/AuthContext";

const font = Roboto({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "JobNest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning={true}
        className={`${font.className} antialiased`}>

        {/* ✅ Wrap everything with AuthProvider */}
        <AuthProvider>
          <Provider>
            <ResponsiveNav />
            {children}
            <Footer />
            <ScrollToTop />
          </Provider>
        </AuthProvider>

      </body>
    </html>
  );
}
